### ISSUE TITLE
Video provider doesnt work

### ISSUE THREAD

**Issue by chocobearxo** [pionxzh/Pornhub.js#25] opened 2022-07-05 18:49 UTC
For some reason, the video provider is always empty and doesnt provide either username or url

**Comment by pionxzh** [comment] 2022-07-15 05:02
They changed the dom structure.
I will try to fix it this weekend.

**Comment by pionxzh** [comment] 2022-09-21 17:56
I just released 0.30 to fix everything but the video, it's quite weird on my side...
I need to take more time to find the root cause

**Comment by pionxzh** [comment] 2022-09-23 18:10
Actually, this one has been fixed in `0.30.0`. What I mentioned before has been moved to https://github.com/pionxzh/Pornhub.js/issues/27 .
Let me know if you still encountered this problem.

**Closed by pionxzh** 2022-09-23 18:10 UTC
Labels: bug
